version: "3.9"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: ic_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    networks:
      - socnet
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: ic_kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - socnet

  zeek:
    image: blacktop/zeek:latest
    container_name: ic_zeek
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./pcaps:/pcaps:ro
      - zeeklogs:/usr/local/zeek/logs
    networks:
      - socnet

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.3
    container_name: ic_filebeat
    user: root
    depends_on:
      - elasticsearch
      - zeek
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - zeeklogs:/var/log/zeek:ro
    networks:
      - socnet

networks:
  socnet:
    driver: bridge

volumes:
  esdata:
  zeeklogs:
