version: "3.9"

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.14.1
    container_name: ic_wazuh_manager
    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
    networks:
      - wznet

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.14.1
    container_name: ic_wazuh_indexer
    networks:
      - wznet

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.14.1
    container_name: ic_wazuh_dashboard
    ports:
      - "8443:5601"
    networks:
      - wznet

networks:
  wznet:
    driver: bridge
