services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  wazuh:
    image: wazuh/wazuh:4.8.0
    depends_on:
      - elasticsearch
    environment:
      - WAZUH_MANAGER=true
    ports:
      - "1514:1514/udp"
      - "55000:55000"

  thehive:
    image: strangebee/thehive:5.3
    depends_on:
      - elasticsearch
    environment:
      - HIVE_OPTS=--no-config-check
    ports:
      - "9000:9000"

  zeek:
    image: blacktop/zeek:latest
    command: ["zeek", "-i", "eth0"]
    network_mode: host

volumes:
  es-data:
